name: NCLA
favicon: null
layout_spectrum: 0.5748235592618585
typography_spectrum: 0.7329224918503314
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#13084d'
    - '#fefefe'
    - '#d83948'
    - '#abadb2'
    - '#62605c'
  brandStrength: 0.3125
  lightness: 0.17171168699860573
  saturation: 0.039226256776601076
  rhythmicContrast: 0.9978529335930943
purpose: []
